# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: levon-toolhub-token
  # token有效期，单位s 默认30天, 7天 = 604800
  timeout: 604800
  # token风格
  token-style: uuid
  # 是否允许同一账号并发登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token
  is-share: false
  # 是否尝试从请求体里读取token
  is-read-body: true
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: true
  # token前缀
  token-prefix: "Bearer"
  # 是否打印操作日志
  is-log: false 