spring:
  application:
    name: levon-toolhub
  # 允许Bean定义覆盖
  main:
    allow-bean-definition-overriding: true
  # 启用彩色输出
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  # Thymeleaf配置
  thymeleaf:
    check-template-location: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/levon_toolhub?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
#  # RabbitMQ配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.levon.toolhub.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      capital-mode: false
    banner: false
    enable-sql-runner: false
    mapper-registry-cache: false

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

## 七牛云配置
#qiniu:
#  access-key: your-access-key
#  secret-key: your-secret-key
#  bucket: your-bucket-name
#  domain: your-domain

## Elasticsearch配置
#elasticsearch:
#  uris: http://localhost:9200
#  username:
#  password:

# 服务器配置
server:
  port: 8018
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    root: info
    com.levon.toolhub: debug

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,mappings
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# 自定义info信息
info:
  app:
    name: Levon ToolHub
    description: 工具分享与评测平台
    version: 1.0.0
  developer:
    name: Levon
    email: contact@example.com
  server:
    java:
      version: ${java.version}
    spring-boot:
      version: ${spring-boot.version}

# 其他配置保持不变 