spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://101.200.141.46:3307/levon_toolhub?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    # 开发环境配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  # Redis配置
  data:
    redis:
      host: 101.200.141.46
      port: 6379
      password:
      database: 0
      timeout: 5000
      # 连接池配置
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数
          max-idle: 8     # 连接池中的最大空闲连接
          min-idle: 0     # 连接池中的最小空闲连接
          max-wait: -1ms  # 连接池最大阻塞等待时间（负数表示没有限制）
          time-between-eviction-runs: 1000  # 空闲连接扫描周期
#  # RabbitMQ配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  # 开发工具配置
  devtools:
    restart:
      enabled: true # 修改pom.xml等项目结构文件后自动重启应用
      additional-paths: src/main/java

      additional-exclude: static/**,public/**
    livereload:
      enabled: true
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

## 七牛云配置
#qiniu:
#  access-key: dev-access-key
#  secret-key: dev-secret-key
#  bucket: dev-bucket
#  domain: dev-domain

## Elasticsearch配置
#elasticsearch:
#  uris: http://localhost:9200
#  username:
#  password:

# 服务器配置
server:
  port: 8022
  servlet:
    context-path: /api

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false

# 日志配置
logging:
  level:
    root: info
    com.levon.toolhub: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug

# MyBatis Plus开发配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.levon.toolhub.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
    enable-sql-runner: false 