spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/levon_toolhub_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 七牛云配置
qiniu:
  access-key: test-access-key
  secret-key: test-secret-key
  bucket: test-bucket
  domain: test-domain

# Elasticsearch配置
elasticsearch:
  uris: http://localhost:9200
  username:
  password:

# 服务器配置
server:
  port: 8081

# 日志配置
logging:
  level:
    root: info
    com.levon.toolhub: debug 